In [12]:
import numpy as np


def expand_matrix(matrix):
    """
    Expand a matrix by mirroring it horizontally (columns) and vertically (rows).
    Given an NxM matrix, produces a (2N)x(2M) matrix where:
      - Each row is concatenated with its reverse.
      - The resulting rows are then concatenated with their reverse order.
    """
    matrix = np.array(matrix)
    mirrored_h = np.hstack([matrix, matrix[:, ::-1]])
    expanded = np.vstack([mirrored_h, mirrored_h[::-1]])
    return expanded


def pretty_print_eigen(matrix, eigenvalues, eigenvectors):
    """Pretty print eigenvalue/eigenvector pairs."""
    order = np.argsort(-np.abs(eigenvalues))

    # Group by unique eigenvalues (within tolerance)
    rounded = np.round(eigenvalues[order].real, 10)
    unique, counts = np.unique(rounded, return_counts=True)
    unique_sorted = unique[np.argsort(-np.abs(unique))]

    print(f"{'─' * 60}")
    print(f"  {'#':<4} {'Eigenvalue':>14}  {'Multiplicity':>12}")
    print(f"{'─' * 60}")
    for i, val in enumerate(unique_sorted):
        mult = counts[unique == val][0]
        print(f"  {i + 1:<4} {val:>14.6f}  {mult:>12}")
    print(f"{'─' * 60}")
    print(f"  Trace (sum of eigenvalues): {np.sum(eigenvalues).real:.6f}")
    print(f"  Determinant (product):      {np.prod(eigenvalues).real:.6f}")
    print(f"  Rank:                        {np.linalg.matrix_rank(matrix)}")
    print(f"{'─' * 60}\n")

    print("  EIGENVECTORS\n")
    for idx in range(len(eigenvalues)):
        i = order[idx]
        val = eigenvalues[i].real
        vec = eigenvectors[:, i].real
        vec_clean = np.where(np.abs(vec) < 1e-10, 0.0, vec)
        print(f"  λ_{idx + 1} = {val:.6f}")
        print(f"  v_{idx + 1} = [{', '.join(f'{x:>8.4f}' for x in vec_clean)}]")
        print()


# --- Demo ---
if __name__ == "__main__":
    original = [
        [1, 1, 1, -1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [-1, 1, 1, 1],
    ]

    result = expand_matrix(original).astype(float)
    result = result + 0.01 * np.identity(len(original) * 2)
    eigenvalues, eigenvectors = np.linalg.eig(result)

    print("Original matrix:")
    print(np.array(original))
    print(f"\nExpanded {len(original)}x{len(original[0])} -> {result.shape[0]}x{result.shape[1]}:")
    print(result)

    print("\n  EIGENVALUE / EIGENVECTOR SUMMARY\n")
    pretty_print_eigen(result, eigenvalues, eigenvectors)

Original matrix:
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [ 1  1  1  1]
 [-1  1  1  1]]

Expanded 4x4 -> 8x8:
[[ 1.01  1.    1.   -1.   -1.    1.    1.    1.  ]
 [ 1.    1.01  1.    1.    1.    1.    1.    1.  ]
 [ 1.    1.    1.01  1.    1.    1.    1.    1.  ]
 [-1.    1.    1.    1.01  1.    1.    1.   -1.  ]
 [-1.    1.    1.    1.    1.01  1.    1.   -1.  ]
 [ 1.    1.    1.    1.    1.    1.01  1.    1.  ]
 [ 1.    1.    1.    1.    1.    1.    1.01  1.  ]
 [ 1.    1.    1.   -1.   -1.    1.    1.    1.01]]

  EIGENVALUE / EIGENVECTOR SUMMARY

────────────────────────────────────────────────────────────
  #        Eigenvalue  Multiplicity
────────────────────────────────────────────────────────────
  1          6.482136             1
  2          4.010000             1
  3         -2.462136             1
  4          0.010000             5
────────────────────────────────────────────────────────────
  Trace (sum of eigenvalues): 8.080000
  Determinant (product):      -0.000000
  Rank:     

In [8]:
import sys
print(sys.path)
sys.path.append('/home/thomas-belcher/MA490')

['/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '', '/home/thomas-belcher/MA490/.venv/lib/python3.12/site-packages']
