The goal of this file is to Solve the SDP problem 

Feasible

Subject to: 
Pr(X - Y) = A_G
tr(Y) <= k 

Fix 1's on the diagonal of the matrix and then solve for frasability using submatrices. 

In [2]:
import sys
import os

sys.path.append(os.path.abspath('..'))



In [3]:
from utils.clique import generate_AG
from utils.clique import generate_AG_bad
# Import packages.
import cvxpy as cp
import numpy as np


In [9]:
# single square graph
maximal_cliques = [
    [0,1],
    [1,2],
    [2,3],
    [3,0]
]
A_G = (generate_AG(4, maximal_cliques))
print(A_G)
n = A_G.shape[0]



for k in range(1, n + 1):
    Y = cp.Variable((n,n), symmetric=True)
    constraints = [Y >> 0, cp.trace(Y) <= k]
    # Impose only known entries

    for i in range(n):
        for j in range(n):
            if A_G[i,j] != 0:
                constraints.append(Y[i,j] == A_G[i,j])

    prob = cp.Problem(cp.Minimize(0), constraints)
    prob.solve()
    if(prob.status == "optimal"):
        
        print("Status:", prob.status)
        print("Solution Y:\n", Y.value)

        # Check rank
        eigvals = np.linalg.eigvalsh(Y.value)
        print("Eigenvalues:", eigvals)
        print("Numerical rank:", np.sum(eigvals > 1e-6))
        break

[[1. 1. 0. 1.]
 [1. 1. 1. 0.]
 [0. 1. 1. 1.]
 [1. 0. 1. 1.]]
Status: optimal
Solution Y:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Eigenvalues: [-2.61253086e-10  2.61135772e-10  2.61140653e-10  4.00000000e+00]
Numerical rank: 1


In [10]:
# large cycle graph
k = 10
maximal_cliques = [[i, (i + 1) % k] for i in range(k)]

print(maximal_cliques)
A_G = (generate_AG(k, maximal_cliques))

n = A_G.shape[0]


for k in range(1, n + 1):
    Y = cp.Variable((n,n), symmetric=True)
    constraints = [Y >> 0, cp.trace(Y) <= k]
    # Impose only known entries

    for i in range(n):
        for j in range(n):
            if A_G[i,j] != 0:
                constraints.append(Y[i,j] == A_G[i,j])

    prob = cp.Problem(cp.Minimize(0), constraints)
    prob.solve()
    if(prob.status == "optimal"):
        
        print("Status:", prob.status)
        print("Solution Y:\n", Y.value)

        # Check rank
        eigvals = np.linalg.eigvalsh(Y.value)
        print("Eigenvalues:", eigvals)
        print("Numerical rank:", np.sum(eigvals > 1e-6))
        break

[[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 0]]
Status: optimal
Solution Y:
 [[1.00000004 1.00000003 1.00004878 1.00004878 1.00004878 1.00004878
  1.00004878 1.00004878 1.00004878 1.00000003]
 [1.00000003 1.00000004 1.00000003 1.00004878 1.00004878 1.00004878
  1.00004878 1.00004878 1.00004878 1.00004878]
 [1.00004878 1.00000003 1.00000004 1.00000003 1.00004878 1.00004878
  1.00004878 1.00004878 1.00004878 1.00004878]
 [1.00004878 1.00004878 1.00000003 1.00000004 1.00000003 1.00004878
  1.00004878 1.00004878 1.00004878 1.00004878]
 [1.00004878 1.00004878 1.00004878 1.00000003 1.00000004 1.00000003
  1.00004878 1.00004878 1.00004878 1.00004878]
 [1.00004878 1.00004878 1.00004878 1.00004878 1.00000003 1.00000004
  1.00000003 1.00004878 1.00004878 1.00004878]
 [1.00004878 1.00004878 1.00004878 1.00004878 1.00004878 1.00000003
  1.00000004 1.00000003 1.00004878 1.00004878]
 [1.00004878 1.00004878 1.00004878 1.00004878 1.00004878 1.00004878
  1.00000003 1.00

In [11]:
# large cycle graph with one negative edge (no solution, k=1)
k = 10
maximal_cliques = [[i, (i + 1) % k] for i in range(k)]

print(maximal_cliques)
A_G = (generate_AG_bad(k, maximal_cliques, bad_edges=[[0,1]]))

n = A_G.shape[0]


for k in range(1, n + 1):
    Y = cp.Variable((n,n), symmetric=True)
    constraints = [Y >> 0, cp.trace(Y) <= k]
    # Impose only known entries

    for i in range(n):
        for j in range(n):
            if A_G[i,j] != 0:
                constraints.append(Y[i,j] == A_G[i,j])

    prob = cp.Problem(cp.Minimize(0), constraints)
    prob.solve()
    if(prob.status == "optimal"):
        
        print("Status:", prob.status)
        print("Solution Y:\n", Y.value)

        # Check rank
        eigvals = np.linalg.eigvalsh(Y.value)
        print("Eigenvalues:", eigvals)
        print("Numerical rank:", np.sum(eigvals > 1e-6))
        break

print("Status:", prob.status)

[[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 0]]
Status: infeasible


In [ ]:
import cvxpy as cp
import numpy as np
from itertools import combinations
# large cycle graph with one negative edge (no solution, k=1)
k = 20
maximal_cliques = [[i, (i + 1) % k] for i in range(k)]

print(maximal_cliques)
A_G = (generate_AG_bad(k, maximal_cliques, bad_edges=[[0,1]]))

n = A_G.shape[0]
k = 1  # number of allowed negative eigenvalues; completion number is the smallest k
num_trials = 100  # number of random subspaces to try
print(A_G)
best_result = None
best_obj = np.inf
eps = 1e-4  # small shift to push near-zero eigenvalues positive
neg_eigenvalues = []
'''
New program to attempt to complete a graph using SDP
Unfortunately completion number is not actually an SDP problem! Specifically, the problem of "remove as many negative eigenvalues as possible" is not convex because we care about the number, not the magnitude.
So instead what we do is add a low dimensional positive semidefinite term in a random subspace, and minimize its trace (which is the sum of the eigenvalues in that subspace).
This could actually add negative eigenvalues in the wrong places, but only a little bit (for reasons I don't fully understand)
That's why we currently force the whole thing to be a little "better" by adding an epsilon.
Also the thing fails sometimes because the optimization is too hard. We now have two dimensions of making it easier: reducing epsilon and increasing k.
'''
for trial in range(num_trials):
    # Random k-dimensional subspace
    V = np.random.randn(n, k)
    V, _ = np.linalg.qr(V)  # orthonormalize to n x k

    Y = cp.Variable((n, n), symmetric=True)
    Alpha = cp.Variable((k, k), PSD=True)

    constraints = [Y - eps*np.eye(n) +V @ Alpha @ V.T >> 0]

    for i in range(n):
        for j in range(n):
            if A_G[i, j] != 0:
                constraints.append(Y[i, j] == A_G[i, j])

    prob = cp.Problem(cp.Minimize(cp.trace(Alpha)), constraints)
    prob.solve()

    if prob.status == "optimal":
        obj = cp.trace(Alpha).value
        eigvals = np.linalg.eigvalsh(Y.value)
        num_neg = np.sum(eigvals < -1e-5) # When it was 6 I was getting a ton. My guess is the computation isn't that precise.

        print(f"Trial {trial}: trace(Alpha) = {obj:.6f}, neg eigenvalues: {num_neg}")
        neg_eigenvalues.append(num_neg)
        if obj < best_obj:
            best_obj = obj
            best_result = Y.value
print((neg_eigenvalues))
print("\nBest solution:")
eigvals = np.linalg.eigvalsh(best_result)
print("Eigenvalues:", np.sort(eigvals))
print("Negative eigenvalues:", np.sum(eigvals < -1e-5))

[[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 10], [10, 11], [11, 12], [12, 13], [13, 14], [14, 15], [15, 16], [16, 17], [17, 18], [18, 19], [19, 0]]


/tmp/ipykernel_17394/1357875057.py:36: UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.
  prob.solve()


Trial 1: trace(Alpha) = 0.531873, neg eigenvalues: 1
Trial 7: trace(Alpha) = 0.568210, neg eigenvalues: 1
Trial 9: trace(Alpha) = 0.357206, neg eigenvalues: 1
Trial 14: trace(Alpha) = 0.314149, neg eigenvalues: 1
Trial 15: trace(Alpha) = 0.343469, neg eigenvalues: 1
Trial 18: trace(Alpha) = 0.416175, neg eigenvalues: 1
Trial 23: trace(Alpha) = 0.503050, neg eigenvalues: 1
Trial 26: trace(Alpha) = 0.438757, neg eigenvalues: 1
Trial 28: trace(Alpha) = 0.357153, neg eigenvalues: 1
Trial 35: trace(Alpha) = 0.412048, neg eigenvalues: 1
Trial 45: trace(Alpha) = 0.417931, neg eigenvalues: 1
Trial 46: trace(Alpha) = 0.237821, neg eigenvalues: 1
Trial 52: trace(Alpha) = 0.339675, neg eigenvalues: 1


In [ ]:
import cvxpy as cp
import numpy as np
from itertools import combinations
# b cycle graphs with one negative edge each (no solution, k=1)

k = 4
b = 3
maximal_cliques = []
bad_edges =[]
for c in range(b):
    offset = c * k
    for i in range(k):
        maximal_cliques.append([offset + i, offset + (i + 1) % k])
    bad_edges.append([offset, offset + 1])
print(maximal_cliques)
print(bad_edges)
A_G = (generate_AG_bad(k * b, maximal_cliques, bad_edges=bad_edges))

n = A_G.shape[0]
k = 1  # number of allowed negative eigenvalues; completion number is the smallest k
num_trials = 100  # number of random subspaces to try

best_result = None
best_obj = np.inf
eps = 1e-4  # small shift to push near-zero eigenvalues positive
neg_eigenvalues = []
for trial in range(num_trials):
    # Random k-dimensional subspace
    V = np.random.randn(n, k)
    V, _ = np.linalg.qr(V)  # orthonormalize to n x k

    Y = cp.Variable((n, n), symmetric=True)
    Alpha = cp.Variable((k, k), PSD=True)

    constraints = [Y - eps*np.eye(n) +V @ Alpha @ V.T >> 0]

    for i in range(n):
        for j in range(n):
            if A_G[i, j] != 0:
                constraints.append(Y[i, j] == A_G[i, j])

    prob = cp.Problem(cp.Minimize(cp.trace(Alpha)), constraints)
    prob.solve()

    if prob.status == "optimal":
        obj = cp.trace(Alpha).value
        eigvals = np.linalg.eigvalsh(Y.value)
        num_neg = np.sum(eigvals < -1e-5) # When it was 6 I was getting a ton. My guess is the computation isn't that precise.

        print(f"Trial {trial}: trace(Alpha) = {obj:.6f}, neg eigenvalues: {num_neg}")
        neg_eigenvalues.append(num_neg)
        if obj < best_obj:
            best_obj = obj
            best_result = Y.value
            print(Y.value)
print((neg_eigenvalues))
print("\nBest solution:")
eigvals = np.linalg.eigvalsh(best_result)
print("Eigenvalues:", np.sort(eigvals))
print("Negative eigenvalues:", np.sum(eigvals < -1e-5))


[[0, 1], [1, 2], [2, 3], [3, 0]]
[[0, 1]]
[[ 1. -1.  0.  1.]
 [-1.  1.  1.  0.]
 [ 0.  1.  1.  1.]
 [ 1.  0.  1.  1.]]
Trial 0: trace(Alpha) = 2.607946, neg eigenvalues: 1
[[ 1.         -1.         -0.40342006  1.        ]
 [-1.          1.          1.         -1.00038215]
 [-0.40342006  1.          1.          1.        ]
 [ 1.         -1.00038215  1.          1.        ]]
Trial 1: trace(Alpha) = 3.726959, neg eigenvalues: 1
Trial 2: trace(Alpha) = 1.452598, neg eigenvalues: 1
[[ 1.         -1.          0.02662016  1.        ]
 [-1.          1.          1.          1.0003003 ]
 [ 0.02662016  1.          1.          1.        ]
 [ 1.          1.0003003   1.          1.        ]]
Trial 3: trace(Alpha) = 1.704354, neg eigenvalues: 1
Trial 4: trace(Alpha) = 7.834282, neg eigenvalues: 1
Trial 5: trace(Alpha) = 1.539737, neg eigenvalues: 1
Trial 6: trace(Alpha) = 1.334683, neg eigenvalues: 1
[[ 1.         -1.         -1.00030411  1.        ]
 [-1.          1.          1.          0.2146655

/tmp/ipykernel_8763/710480745.py:43: UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.
  prob.solve()


Trial 11: trace(Alpha) = 1.494244, neg eigenvalues: 1
Trial 12: trace(Alpha) = 2.342800, neg eigenvalues: 1
Trial 13: trace(Alpha) = 4.248920, neg eigenvalues: 1
Trial 14: trace(Alpha) = 1.721974, neg eigenvalues: 1
Trial 15: trace(Alpha) = 3.096374, neg eigenvalues: 1
Trial 16: trace(Alpha) = 1.574772, neg eigenvalues: 1
Trial 17: trace(Alpha) = 2.269840, neg eigenvalues: 1
Trial 19: trace(Alpha) = 1.618164, neg eigenvalues: 1
Trial 21: trace(Alpha) = 1.162296, neg eigenvalues: 1
[[ 1.00000003 -1.00000001 -1.00055496  1.00000003]
 [-1.00000001  1.00000002  1.00000002 -0.63203686]
 [-1.00055496  1.00000002  1.00000006  1.00000004]
 [ 1.00000003 -0.63203686  1.00000004  1.00000008]]
Trial 22: trace(Alpha) = 1.589999, neg eigenvalues: 1
Trial 24: trace(Alpha) = 52.275361, neg eigenvalues: 1
Trial 25: trace(Alpha) = 1.437232, neg eigenvalues: 1
Trial 26: trace(Alpha) = 1.357295, neg eigenvalues: 1
Trial 28: trace(Alpha) = 1.851639, neg eigenvalues: 1
Trial 29: trace(Alpha) = 1.262604, neg

In [ ]:
import cvxpy as cp
import numpy as np
from itertools import combinations
from finding_completion.tiling import tile_top_left_4x4
# confirming functionality using known bad matrix (counterexample from paper)

k = 4
b = 3
A_G = np.array(tile_top_left_4x4(3))
n = A_G.shape[0]
k = 3  # number of allowed negative eigenvalues; completion number is the smallest k
num_trials = 100  # number of random subspaces to try

best_result = None
best_obj = np.inf
eps = 1e-6  # small shift to push near-zero eigenvalues positive
neg_eigenvalues = []
for trial in range(num_trials):
    if (trial % 10 == 0):
        print("trial " + str(trial))
    # Random k-dimensional subspace
    V = np.random.randn(n, k)
    V, _ = np.linalg.qr(V)  # orthonormalize to n x k

    Y = cp.Variable((n, n), symmetric=True)
    Alpha = cp.Variable((k, k), PSD=True)

    constraints = [Y - eps*np.eye(n) + V @ Alpha @ V.T >> 0]

    for i in range(n):
        for j in range(n):
            if A_G[i, j] != None:
                constraints.append(Y[i, j] == A_G[i, j])

    prob = cp.Problem(cp.Minimize(cp.trace(Alpha)), constraints)
    prob.solve()

    if prob.status == "optimal":
        obj = cp.trace(Alpha).value
        eigvals = np.linalg.eigvalsh(Y.value)
        num_neg = np.sum(eigvals < -1e-5)

        print(f"Trial {trial}: trace(Alpha) = {obj:.6f}, neg eigenvalues: {num_neg}")
        neg_eigenvalues.append(num_neg)
        if obj < best_obj:
            best_obj = obj
            best_result = Y.value
            print(Y.value)
print((neg_eigenvalues))
print("\nBest solution:")
eigvals = np.linalg.eigvalsh(best_result)
print("Eigenvalues:", np.sort(eigvals))
print("Negative eigenvalues:", np.sum(eigvals < -1e-5))
# Apparently the PSD solver can't handle this as written. My guess is that this version scales in difficulty to roughly the number of *constraints* and this has a ton.
# Claude's brute forcey solver, on the other hand, can do these types of problems easily but struggles when there are too many options.

trial 0


/tmp/ipykernel_8763/2234078139.py:36: UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.
  prob.solve()


trial 10
trial 20
trial 30
trial 40
trial 50
trial 60
trial 70
trial 80
trial 90
[]

Best solution:


LinAlgError: 0-dimensional array given. Array must be at least two-dimensional