The goal of this file is to Solve the SDP problem 

Feasible

Subject to: 
Pr(X - Y) = A_G
tr(Y) <= k 

Fix 1's on the diagonal of the matrix and then solve for frasability using submatrices. 

In [ ]:
import sys
import os

sys.path.append(os.path.abspath('..'))



In [11]:
from utils.clique import generate_AG
# Import packages.
import cvxpy as cp
import numpy as np


In [9]:
maximal_cliques = [
    [0,1],
    [1,2],
    [2,3],
    [3,0]
]
A_G = (generate_AG(4, maximal_cliques))


In [18]:
n = A_G.shape[0]



for k in range(1, n + 1):
    Y = cp.Variable((n,n), symmetric=True)
    constraints = [Y >> 0, cp.trace(Y) <= k]
    # Impose only known entries

    for i in range(n):
        for j in range(n):
            if A_G[i,j] != 0:
                constraints.append(Y[i,j] == A_G[i,j])

    prob = cp.Problem(cp.Minimize(0), constraints)
    prob.solve()
    if(prob.status == "optimal"):
        
        print("Status:", prob.status)
        print("Solution Y:\n", Y.value)

        # Check rank
        eigvals = np.linalg.eigvalsh(Y.value)
        print("Eigenvalues:", eigvals)
        print("Numerical rank:", np.sum(eigvals > 1e-6))
        break

Status: optimal
Solution Y:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Eigenvalues: [-2.61247788e-10  2.61131097e-10  2.61133153e-10  4.00000000e+00]
Numerical rank: 1
