In [2]:
# Import packages.
import cvxpy as cp
import numpy as np

In [15]:
A1 = [[1, 0, 1], [0, 3, 7], [1, 7, 5] ]
A1 = np.array(A1)

A2 = [[0,2,8], [2, 6, 0], [8,0,4]]
A2 = np.array(A2)

C = [[1,2,3,], [2,9,0],[3,0,7]]
C = np.array(C)

b1 = 11
b2 = 19

X = cp.Variable((3,3), symmetric=True)

In [18]:
constraints = [X >> 0] 
constraints += [(cp.vdot(A1, X) == b1)]
constraints += [(cp.vdot(A2, X) == b2)]

In [19]:
prob = cp.Problem(cp.Minimize(cp.vdot(C, X)), constraints)
prob.solve()

# Print result.
print("The optimal value is", prob.value)
print("A solution X is")
print(X.value)

The optimal value is 13.902182526039677
A solution X is
[[1.05600838 0.36917833 0.86830385]
 [0.36917833 0.12907089 0.30358367]
 [0.86830385 0.30358367 0.71399996]]


This problem was taken from: https://ocw.mit.edu/courses/6-251j-introduction-to-mathematical-programming-fall-2009/08bbc2660764c4f61bde5363ae134339_MIT6_251JF09_SDP.pdf
And the package used is cvxpy