In [3]:
import numpy as np

matrix = np.zeros((6, 6))
np.fill_diagonal(matrix, -1.0)
np.fill_diagonal(np.fliplr(matrix), 1000.0)

print(matrix)
print(matrix)

eigenvalues = np.linalg.eigvalsh(matrix)

print("Eigenvalues (sorted ascending):")
for i, val in enumerate(eigenvalues):
    print(f"  λ{i+1} = {val: .8f}")

print(f"\nPositive semi-definite: {np.all(eigenvalues >= -1e-10)}")
print(f"Min eigenvalue: {eigenvalues.min():.8f}")
print(f"Max eigenvalue: {eigenvalues.max():.8f}")
print(f"Trace (sum of eigenvalues): {eigenvalues.sum():.8f}")

[[  -1.    0.    0.    0.    0. 1000.]
 [   0.   -1.    0.    0. 1000.    0.]
 [   0.    0.   -1. 1000.    0.    0.]
 [   0.    0. 1000.   -1.    0.    0.]
 [   0. 1000.    0.    0.   -1.    0.]
 [1000.    0.    0.    0.    0.   -1.]]
[[  -1.    0.    0.    0.    0. 1000.]
 [   0.   -1.    0.    0. 1000.    0.]
 [   0.    0.   -1. 1000.    0.    0.]
 [   0.    0. 1000.   -1.    0.    0.]
 [   0. 1000.    0.    0.   -1.    0.]
 [1000.    0.    0.    0.    0.   -1.]]
Eigenvalues (sorted ascending):
  λ1 = -1001.00000000
  λ2 = -1001.00000000
  λ3 = -1001.00000000
  λ4 =  999.00000000
  λ5 =  999.00000000
  λ6 =  999.00000000

Positive semi-definite: False
Min eigenvalue: -1001.00000000
Max eigenvalue: 999.00000000
Trace (sum of eigenvalues): -6.00000000
